services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: aiogram_bot
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
